name: ci

on:
  push:
    branches: master
    paths:
        - python/**
        - scripts/**
        - config/**
        - Dockerfile.prod
        - requirements.txt
        - run.sh
        - .github/workflows/build_docker.yaml
env:
  tag: ${{ github.sha }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "sztanko/solsticestreets_prod:latest, sztanko/solsticestreets_prod:${{ env.tag }}"
          file: Dockerfile.prod
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}