name: build_site

on:
  push:
    branches: master
    paths:
      - site/**
      - .github/workflows/buid_site.yaml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        uses: borales/actions-yarn@v2.0.0
        run: |
          cd site
          yarn install
          yarn export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages2 # The branch the action should deploy to.
          folder: site/out # The folder the action should deploy.
